# Generated by Django 4.1.3 on 2024-04-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeaderSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hx",
                    models.CharField(
                        choices=[
                            ("h1", "H1"),
                            ("h2", "H2"),
                            ("h3", "H3"),
                            ("h4", "H4"),
                            ("h5", "H5"),
                            ("h6", "H6"),
                        ],
                        default="h1",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(blank=True, default="", null=True)),
            ],
        ),
    ]
