# Generated by Django 4.1.3 on 2024-06-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("header", "0002_alter_headersnippet_hx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headersnippet",
            name="hx",
            field=models.CharField(
                blank=True,
                choices=[
                    ("h1", "H1"),
                    ("h2", "H2"),
                    ("h3", "H3"),
                    ("h4", "H4"),
                    ("h5", "H5"),
                    ("h6", "H6"),
                ],
                default="h1",
                max_length=10,
            ),
        ),
    ]
