# Generated by Django 4.1.3 on 2023-01-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_snippet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_snippet",
                        to="snippets.snippet",
                    ),
                ),
                (
                    "footer_snippet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="footer_snippet",
                        to="snippets.snippet",
                    ),
                ),
                (
                    "header_snippet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="header_snippet",
                        to="snippets.snippet",
                    ),
                ),
            ],
        ),
    ]
