# Generated by Django 4.1.3 on 2023-08-07 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0005_alter_basesnippet_type"),
        ("page_structure", "0002_alter_pagestructure_content_snippet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagestructure",
            name="content_snippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_snippet",
                to="snippets.basesnippet",
            ),
        ),
        migrations.AlterField(
            model_name="pagestructure",
            name="footer_snippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="footer_snippet",
                to="snippets.basesnippet",
            ),
        ),
        migrations.AlterField(
            model_name="pagestructure",
            name="header_snippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="header_snippet",
                to="snippets.basesnippet",
            ),
        ),
    ]
