# Generated by Django 4.1.3 on 2023-08-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publisher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="execution_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
