apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
data:
    DEBUG: "1"
    SECRET_KEY: "infoboard_secret_key"
    ALLOWED_HOSTS: "*"
    DB_NAME: "default"
    DB_NAME_PUBLIC: "public"
    DB_USERNAME: "admin"
    DB_USERNAME_PUBLIC: "admin"
    DB_PASSWORD: "admin"
    DB_PASSWORD_PUBLIC: "admin"
    DB_HOST: "db-default"
    DB_HOST_PUBLIC: "db-public"
    DB_PORT: "5432"
    DB_PUBLIC_PORT: "5432"
    CORS_ALLOWED_ORIGINS: "http://0.0.0.0:8000"
    CSRF_TRUSTED_ORIGINS: "http://0.0.0.0:8000"
    IS_PRODUCTION: "0"
    IS_FRONT: "1"
    IS_CMS: "0"
    REDIS_HOST: "redis"
    ES_HOST: "es"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          imagePullPolicy: IfNotPresent
          image: wronamichal/infoboard
          envFrom:
            - configMapRef:
                name: front-config
          command: ["./manage.py", "runserver", "0.0.0.0:8000"]
          ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front-service
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - port: 8000
      targetPort: 8000