version: "3.8"

services:
  front:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    container_name: infoboard_front
    env_file:
      - envs/local/web/front/env.front
    depends_on:
      - db_default
      - db_public

  cms:
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    command: python manage.py runserver 0.0.0.0:8001
    container_name: infoboard_cms
    env_file:
      - envs/local/web/cms/env.cms
    depends_on:
      - db_default
      - db_public
      - front

  db_default:
    image: postgres:15.1-bullseye
    volumes:
      - postgres_data_default:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    container_name: infoboard_db_default
    env_file:
      - envs/local/db/env.default

  db_public:
    image: postgres:15.1-bullseye
    volumes:
      - postgres_data_public:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    container_name: infoboard_db_public
    env_file:
      - envs/local/db/env.public

volumes:
  postgres_data_default:
  postgres_data_public: