version: "3.3"

services:
  infoboard_front:
    build: .
    volumes:
      - .:/code
    expose:
      - "8000"
    command: gunicorn --workers=8 infoboard.wsgi:application --bind 0.0.0.0:8000 --timeout 1000 --log-level=info --log-file=./logs/gunicorn_front.log --access-logfile=./logs/gunicorn-access_front.log
    container_name: infoboard_front
    env_file:
      - envs/prod/web/front/env.front
    depends_on:
      - db_default
      - db_public
      #- es
    networks:
      - infoboard_network

  infoboard_cms:
    build: .
    volumes:
      - .:/code
    expose:
      - "8001"
    command: gunicorn --workers=1 infoboard.wsgi:application --bind 0.0.0.0:8001 --log-level=info --log-file=./logs/gunicorn_cms.log --access-logfile=./logs/gunicorn-access_cms.log
    container_name: infoboard_cms
    env_file:
      - envs/prod/web/cms/env.cms
    depends_on:
      - db_default
      - db_public
      - infoboard_front
      #- es
    networks:
      - infoboard_network

  nginx_infoboard_front:
    container_name: nginx_infoboard_front
    restart: always
    build: ./nginx_front
    volumes:
      - /var/www/InfoBoard/staticfiles:/var/www/InfoBoard/staticfiles
    ports:
      - "8081:8081"
    depends_on:
      - infoboard_cms
      - infoboard_front
      - db_default
      - db_public
      #- es
    networks:
      - infoboard_network

  nginx_infoboard_cms:
    container_name: nginx_infoboard_cms
    restart: always
    build: ./nginx_cms
    volumes:
      - /var/www/InfoBoard/staticfiles:/var/www/InfoBoard/staticfiles
    ports:
      - "8082:8082"
    depends_on:
      - infoboard_cms
      - infoboard_front
      - db_default
      - db_public
      #- es
    networks:
      - infoboard_network

  db_default:
    image: postgres:15.1-bullseye
    volumes:
      - postgres_data_default:/var/lib/postgresql/data/
    expose:
      - "5432"
    container_name: infoboard_db_default
    env_file:
      - envs/prod/db/env.default
    environment:
      PGTZ: 'Europe/Warsaw'
      TZ: 'Europe/Warsaw'
    networks:
      - infoboard_network

  db_public:
    image: postgres:15.1-bullseye
    volumes:
      - postgres_data_public:/var/lib/postgresql/data/
    expose:
      - "5432"
    container_name: infoboard_db_public
    env_file:
      - envs/prod/db/env.public
    environment:
      PGTZ: 'Europe/Warsaw'
      TZ: 'Europe/Warsaw'
    networks:
      - infoboard_network

#  es:
#    container_name: es
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
#    environment:
#      - node.name=es
#      - cluster.name=es-docker
#      - discovery.type=single-node
#      - bootstrap.memory_lock=false
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - es_data:/usr/share/elasticsearch/data
#    expose:
#      - "9200"
#    networks:
#      - infoboard_network


  redis:
    image: redis:alpine
    networks:
      - infoboard_network

volumes:
  postgres_data_default:
  postgres_data_public:
  es_data:

networks:
  infoboard_network:
    external: true