version: "3.3"

services:
  infoboard_front:
    restart: always
    image: wronamichal/infoboard:latest
    volumes:
      - .:/code
    expose:
      - "8000"
    command: gunicorn --workers=2 infoboard.wsgi:application --bind 0.0.0.0:8000 --timeout 10000 --log-level=info --log-file=./logs/gunicorn_front.log --access-logfile=./logs/gunicorn-access_front.log
    container_name: infoboard_front
    env_file:
      - envs/prod/web/front/env.front
    depends_on:
      - db_default
      - db_public
    networks:
      - infoboard_network

  infoboard_cms:
    image: wronamichal/infoboard:latest
    volumes:
      - .:/code
    expose:
      - "8001"
    command: gunicorn --workers=2 infoboard.wsgi:application --bind 0.0.0.0:8001 --log-level=info --log-file=./logs/gunicorn_cms.log --access-logfile=./logs/gunicorn-access_cms.log
    container_name: infoboard_cms
    env_file:
      - envs/prod/web/cms/env.cms
    depends_on:
      - db_default
      - db_public
      - infoboard_front
    networks:
      - infoboard_network

  nginx_infoboard_front:
    container_name: nginx_infoboard_front
    restart: always
    build: ./nginx_front
    volumes:
      - /var/www/InfoBoard/staticfiles:/var/www/InfoBoard/staticfiles
    ports:
      - "8081:8081"
    depends_on:
      - infoboard_cms
      - infoboard_front
      - db_default
      - db_public
    networks:
      - infoboard_network

  nginx_infoboard_cms:
    container_name: nginx_infoboard_cms
    restart: always
    build: ./nginx_cms
    volumes:
      - /var/www/InfoBoard/staticfiles:/var/www/InfoBoard/staticfiles
    ports:
      - "8082:8082"
    depends_on:
      - infoboard_cms
      - infoboard_front
      - db_default
      - db_public
    networks:
      - infoboard_network

  db_default:
    image: postgres:15.1-bullseye
    volumes:
      - postgres_data_default:/var/lib/postgresql/data/
    expose:
      - "5432"
    container_name: infoboard_db_default
    env_file:
      - envs/prod/db/env.default
    environment:
      PGTZ: 'Europe/Warsaw'
      TZ: 'Europe/Warsaw'
    networks:
      - infoboard_network

  db_public:
    image: postgres:15.1-bullseye
    volumes:
      - postgres_data_public:/var/lib/postgresql/data/
    expose:
      - "5432"
    container_name: infoboard_db_public
    env_file:
      - envs/prod/db/env.public
    environment:
      PGTZ: 'Europe/Warsaw'
      TZ: 'Europe/Warsaw'
    networks:
      - infoboard_network

  publisher:
    image: wronamichal/infoboard:latest
    volumes:
      - .:/code
    command: python3 manage.py publisher
    container_name: publisher
    env_file:
      - envs/prod/web/publisher/env.publisher
    depends_on:
      - db_default
      - db_public
    networks:
      - infoboard_network
    deploy:
      replicas: 0

volumes:
  postgres_data_default:
  postgres_data_public:

networks:
  infoboard_network:
    external: true