version: "3.3"

services:
  infoboard_front:
    build: .
    volumes:
      - .:/code
    expose:
      - "8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: infoboard_front
    restart: always
    env_file:
      - envs/local_pr/web/front/env.front
    depends_on:
      - db_default
      - db_public
    networks:
      infoboard_network:
        ipv4_address: 172.21.0.2

  infoboard_cms:
    build: .
    volumes:
      - .:/code
    expose:
      - "8001"
    command: python3 manage.py runserver 0.0.0.0:8001
    restart: always
    container_name: infoboard_cms
    env_file:
      - envs/local_pr/web/cms/env.cms
    depends_on:
      - db_default
      - db_public
      - infoboard_front
    networks:
      infoboard_network:
        ipv4_address: 172.21.0.3

  infoboard_publisher:
    build: .
    volumes:
      - .:/code
    command: python3 manage.py publisher
    restart: always
    env_file:
      - envs/local_pr/web/publisher/env.publisher
    depends_on:
      - db_default
      - db_public
      - infoboard_cms
      - infoboard_front
    networks:
      infoboard_network:
        ipv4_address: 172.21.0.4

  nginx-infoboard-front:
    container_name: nginx-infoboard-front
    restart: always
    build: ./nginx-local_front
    volumes:
      - /home/michal/workspaces/InfoBoard/staticfiles:/var/www/InfoBoard/staticfiles
      - /home/michal/workspaces/InfoBoard/static:/var/www/InfoBoard/static
    expose:
      - "8081"
    depends_on:
      - infoboard_cms
      - infoboard_front
      - db_default
      - db_public
    networks:
      infoboard_network:
        ipv4_address: 172.21.0.5


  nginx-infoboard-cms:
    container_name: nginx-infoboard-cms
    restart: always
    build: ./nginx-local_cms
    volumes:
      - /home/michal/workspaces/InfoBoard/staticfiles:/var/www/InfoBoard/staticfiles
      - /home/michal/workspaces/InfoBoard/static:/var/www/InfoBoard/static
    expose:
      - "8082"
    depends_on:
      - infoboard_cms
      - infoboard_front
      - db_default
      - db_public
    networks:
      infoboard_network:
        ipv4_address: 172.21.0.6

  db_default:
    image: postgres:15.1-bullseye
    volumes:
      - postgres_data_default:/var/lib/postgresql/data/
    expose:
      - "5432"
    container_name: infoboard_db_default
    restart: always
    env_file:
      - envs/local_pr/db/env.default
    environment:
      PGTZ: 'Europe/Warsaw'
      TZ: 'Europe/Warsaw'
    networks:
      infoboard_network:
        ipv4_address: 172.21.0.7

  db_public:
    image: postgres:15.1-bullseye
    volumes:
      - postgres_data_public:/var/lib/postgresql/data/
    expose:
      - "5432"
    container_name: infoboard_db_public
    restart: always
    env_file:
      - envs/local_pr/db/env.public
    environment:
      PGTZ: 'Europe/Warsaw'
      TZ: 'Europe/Warsaw'
    networks:
      infoboard_network:
        ipv4_address: 172.21.0.8


  varnish:
    restart: always
    container_name: varnish
    build: ./varnish-local
    volumes:
      - ./varnish-local/default.vcl:/etc/varnish/default.vcl
    ports:
      - "80:80"
    tmpfs:
      - /var/lib/varnish:exec
    command: "-p default_keep=300"
    depends_on:
      - nginx-infoboard-front
      - nginx-infoboard-cms
    environment:
      - VARNISH_SIZE=2G
    networks:
      infoboard_network:
        ipv4_address: 172.21.0.9

volumes:
  postgres_data_default:
  postgres_data_public:

networks:
  infoboard_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1