apiVersion: v1
kind: ConfigMap
metadata:
  name: cms-config
data:
    DEBUG: "1"
    SECRET_KEY: "infoboard_secret_key"
    ALLOWED_HOSTS: "*"
    DB_NAME: "cms"
    DB_NAME_PUBLIC: "public"
    DB_USERNAME: "postgres"
    DB_USERNAME_PUBLIC: "admin"
    DB_PASSWORD: "infoboard-admin"
    DB_PASSWORD_PUBLIC: "infoboard-admin"
    DB_HOST: "34.118.23.61"
    DB_HOST_PUBLIC: "34.118.23.61"
    DB_PORT: "5432"
    DB_PUBLIC_PORT: "5432"
    CORS_ALLOWED_ORIGINS: "http://0.0.0.0:8000"
    CSRF_TRUSTED_ORIGINS: "http://0.0.0.0:8000"
    IS_PRODUCTION: "0"
    IS_FRONT: "0"
    IS_CMS: "1"
    REDIS_HOST: "redis"
    ES_HOST: "es"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  labels:
    app: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
        - name: cms
          imagePullPolicy: IfNotPresent
          image: wronamichal/infoboard
          envFrom:
            - configMapRef:
                name: cms-config
          command: ["./manage.py", "runserver", "0.0.0.0:8001"]
          ports:
          - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: cms-service
  labels:
    app: cms-service
spec:
  type: NodePort
  selector:
    app: cms
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8001
