# Generated by Django 4.1.3 on 2023-10-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("html", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htmlsnippet",
            name="html",
            field=models.TextField(blank=True, null=True),
        ),
    ]
