# Generated by Django 4.1.3 on 2024-04-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("html", "0002_alter_htmlsnippet_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htmlsnippet",
            name="html",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
