# Generated by Django 4.1.3 on 2023-04-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
        ("video_snippet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoPositionSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video.video",
                    ),
                ),
                (
                    "video_snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_snippet.videosnippet",
                    ),
                ),
            ],
        ),
    ]
