# Generated by Django 4.1.3 on 2023-04-01 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video_snippet", "0002_videopositionsnippet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videosnippet",
            name="videos",
        ),
    ]
