# Generated by Django 4.1.3 on 2023-08-07 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_snippet", "0003_remove_videosnippet_videos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videopositionsnippet",
            name="video_snippet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="video_snippet.videosnippet",
            ),
        ),
    ]
