apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-public
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-public
  template:
    metadata:
      labels:
        app: postgres-public
    spec:
      initContainers:
      - name: init-postgres
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/lib/postgresql/data/pgdata-public && chown -R 999:999 /var/lib/postgresql/data-public']
        volumeMounts:
        - mountPath: /var/lib/postgresql/data-public
          name: postgres-storage-public
      containers:
      - name: postgres-public
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: public
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata-public
        volumeMounts:
        - mountPath: /var/lib/postgresql/data-public
          name: postgres-storage-public
      volumes:
      - name: postgres-storage-public
        persistentVolumeClaim:
          claimName: postgres-pvc-public
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-public
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-public
