# Generated by Django 4.1.3 on 2023-03-04 21:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wyswig", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyswigsnippet",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
