apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infoboard-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varnish
            port:
              number: 80
