# Generated by Django 4.1.3 on 2023-01-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.DateTimeField(auto_created=True, auto_now=True)),
                ("created", models.DateTimeField(auto_created=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("wyswig_snippet", "Wyswig")], max_length=200
                    ),
                ),
                ("snippet_id", models.IntegerField()),
            ],
        ),
    ]
