# Generated by Django 4.1.3 on 2023-02-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="snippet_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("wyswig_snippet", "Wyswig")],
                max_length=200,
                null=True,
            ),
        ),
    ]
