# Generated by Django 4.1.3 on 2023-02-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0002_alter_snippet_snippet_id_alter_snippet_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="created",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
