# Generated by Django 4.1.3 on 2023-03-04 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("page_structure", "0001_initial"),
        ("snippets", "0003_alter_snippet_created"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Snippet",
            new_name="BaseSnippet",
        ),
    ]
