# Generated by Django 4.1.3 on 2023-03-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0004_rename_snippet_basesnippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basesnippet",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("wyswig_snippet", "Wyswig"), ("video_snippet", "Video")],
                max_length=200,
                null=True,
            ),
        ),
    ]
