# Generated by Django 4.1.3 on 2023-10-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0005_alter_basesnippet_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="HtmlSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="basesnippet",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wyswig_snippet", "Wyswig"),
                    ("video_snippet", "Video"),
                    ("html_snippet", "HTML"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
