# Generated by Django 4.1.3 on 2023-10-15 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0006_htmlsnippet_alter_basesnippet_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HtmlSnippet",
        ),
    ]
