apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-configmap
data:
  default.vcl: |
    vcl 4.1;

    backend cms {
        .host = "cms-service";
        .port = "8080";
    }
    
    backend front {
        .host = "front-service";
        .port = "8081";
    }
        
    sub vcl_recv {
        if (req.http.host == "infoboard-kubernetes.michalwrona.local.pl") {
            set req.backend_hint = front;
        } else {
            set req.backend_hint = cms;
        }  
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
  labels:
    app: varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      labels:
        app: varnish
    spec:
      containers:
      - name: varnish
        image: varnish:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: varnish-config
          mountPath: /etc/varnish
      volumes:
      - name: varnish-config
        configMap:
          name: varnish-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: varnish
  labels:
    app: varnish
spec:
  type: NodePort
  selector:
    app: varnish
  ports:
  - name: http
    port: 80
    targetPort: 80