# Generated by Django 4.1.3 on 2023-02-02 16:57

import re

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("page_structure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.DateTimeField(auto_created=True, auto_now=True)),
                ("created", models.DateTimeField(auto_created=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "slug",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                "invalid",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Kopia robocza"),
                            (2, "Do publikacji"),
                            (3, "Opublikowany"),
                            (4, "Do archiwum"),
                            (5, "Archiwalny"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("descripton", models.CharField(max_length=500)),
                ("publish_from", models.DateTimeField()),
                ("publish_to", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page_structure",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="page_structure.pagestructure",
                    ),
                ),
            ],
        ),
    ]
