# Generated by Django 4.1.3 on 2023-02-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='descripton',
            new_name='description',
        ),
    ]
