# Generated by Django 4.1.3 on 2023-02-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0003_alter_page_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="publish_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
