# Generated by Django 4.1.3 on 2023-02-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0004_alter_page_publish_to_alter_page_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Nowa kopia robocza"),
                    (2, "Do publikacji"),
                    (3, "Opublikowany"),
                    (4, "Do archiwum"),
                    (5, "Archiwalny"),
                ],
                default=1,
                max_length=1,
            ),
        ),
    ]
