# Generated by Django 4.1.3 on 2023-03-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0005_alter_page_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
