# Generated by Django 4.1.3 on 2023-03-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0006_alter_page_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="page",
            name="created",
            field=models.DateTimeField(auto_created=True),
        ),
    ]
