# Generated by Django 4.1.3 on 2023-03-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0007_alter_page_options_alter_page_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="created",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
